name: Cypress Tests

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: 6.30.1
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Build extension
        run: pnpm build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm run serve
          wait-on: 'http://localhost:3000'
